### ISSUE TITLE
round doesn't work properly with negative numbers

### ISSUE THREAD

**Issue by LeonB** [joelpurra/jq-math#1]
```
$ echo '{}' | jq 'import "jqs/jq-math" as Math; -36.475 | Math::round(2)'
-36.47
$ echo '{}' | jq 'import "jqs/jq-math" as Math; 36.475 | Math::round(2)'
36.48`
```

**Comment by joelpurra** [comment]
@LeonB: ah, yes. Depends on your preferred variant of rounding I guess, but I see what you mean. Will implement the round half away from zero tie-breaker rule.

Didn't have any negative test cases before, but added yours and a few more.

See

- https://en.wikipedia.org/wiki/Rounding

**Comment by joelpurra** [comment]
@LeonB: thanks for the error report! Let me know if you find anything other problems, including in #2.

**Comment by LeonB** [comment]
@joelpurra thanks for the quick fix!
